// Legal pages — privacy notice and terms of engagement.
// These documents reflect the firm's current practice and are drafted to
// be read by clients and prospective clients. They are not bespoke legal
// advice and may be revised by the firm without notice.

export const privacyCopy = {
  effectiveDate: "2026-05-01",

  intro: [
    "This notice explains how Gazi & Associates collects, uses and protects personal information in the course of its work. It applies to information collected through the firm's website, the consultation enquiry form, and direct correspondence with the firm's chambers.",
    "The firm collects only the personal information it needs to advise existing and prospective clients and to operate as a regulated legal practice in Bangladesh.",
  ],

  sections: [
    {
      heading: "Who we are",
      paragraphs: [
        "Gazi & Associates is a commercial law firm with chambers in Dhaka, Jashore and London. The firm acts as data controller in respect of personal information it collects through the channels described in this notice.",
        "The firm's principal address for data-protection purposes is its Dhaka chamber: Room 06, 4th Floor, GA Bhaban, 8 Purana Paltan, Dhaka 1000. Enquiries about this notice may be sent to chambers@gazilegal.com.",
      ],
    },
    {
      heading: "What we collect",
      paragraphs: [
        "Information you provide. When a prospective client submits the consultation enquiry form, the firm collects the name, organisation (if supplied), jurisdiction, matter type and the description of the matter that the prospective client enters into the form.",
        "Information from correspondence. When existing or prospective clients write to the firm by email or call the firm's chambers, the firm collects the contact details and content of that correspondence.",
        "Information from client engagements. When the firm is instructed on a matter, it collects the information needed to act on that matter — typically identity documents, corporate records, financial and tax information, and correspondence with counterparties, regulators and the courts.",
        "Server logs. The firm's website is hosted on Vercel, which records standard server logs (IP address, user agent, timestamp) for the purpose of operating and securing the site. The firm does not use these logs to identify individual visitors and does not deploy analytics or advertising trackers on the site.",
      ],
    },
    {
      heading: "Why we use it",
      paragraphs: [
        "The firm uses personal information for three purposes: to respond to enquiries and consider whether to accept instructions; to act on the matters on which it is instructed; and to comply with the firm's legal and regulatory obligations under Bangladesh law, including the regulatory framework administered by the Bangladesh Bar Council.",
        "For matters connected with the firm's London chamber, the firm may also process personal information to comply with the United Kingdom data-protection regime where it applies.",
      ],
    },
    {
      heading: "How we share it",
      paragraphs: [
        "The firm does not sell personal information and does not share it for marketing purposes.",
        "The firm uses Resend (a third-party email delivery service) to send correspondence generated by the consultation form to the firm's chamber email. Resend processes message content and recipient data on the firm's behalf.",
        "The firm may share information with the courts, regulators and counterparties where doing so is necessary to act on a client's matter, where required by law, or where the client has authorised it.",
      ],
    },
    {
      heading: "How long we keep it",
      paragraphs: [
        "Consultation enquiries that do not result in an engagement are retained for up to 12 months and then deleted.",
        "Client files are retained for the period required by the firm's professional conduct obligations and the Limitation Act 1908, typically seven years from the conclusion of the matter, after which records are securely destroyed unless the firm has been instructed to hold them for longer.",
      ],
    },
    {
      heading: "Your rights",
      paragraphs: [
        "Individuals whose personal information the firm holds may request access to that information, request that it be corrected, or request that it be deleted where the firm is no longer required to hold it. Requests may be made by email to chambers@gazilegal.com.",
        "The firm will respond to requests within a reasonable period and may require verification of identity before responding.",
      ],
    },
    {
      heading: "Changes to this notice",
      paragraphs: [
        "The firm may update this notice from time to time. The current version is the version published on this page; the effective date is shown above.",
      ],
    },
  ],
} as const;

export const termsCopy = {
  effectiveDate: "2026-05-01",

  intro: [
    "These terms set out the basis on which Gazi & Associates accepts and conducts instructions. They are read together with the firm's engagement letter for a particular matter, which describes the scope of work and the fees applicable to that matter.",
    "Where there is any inconsistency between these terms and the engagement letter, the engagement letter prevails.",
  ],

  sections: [
    {
      heading: "Acceptance of instructions",
      paragraphs: [
        "The firm accepts instructions in writing. Until the firm has confirmed acceptance and the conflict and identity checks described below have been completed, no solicitor–client relationship exists between the firm and the prospective client.",
        "The firm does not act on every matter that is offered to it. Acceptance is subject to availability, the absence of conflict, and the firm's assessment that it can act effectively for the client on the matter proposed.",
      ],
    },
    {
      heading: "Scope of work and fees",
      paragraphs: [
        "The scope of work for each matter is set out in the engagement letter and is limited to the work described there. Additional work that falls outside that scope is the subject of a written variation.",
        "Fees are agreed in writing at the outset of every engagement. The firm acts on the basis of agreed fixed fees, time-based fees or a combination of the two; the basis applicable to a particular matter is set out in the engagement letter.",
        "Disbursements (court fees, registration fees, stamp duty, translation costs, and similar items) are charged at cost and itemised on the firm's invoices.",
      ],
    },
    {
      heading: "Conflict and identity checks",
      paragraphs: [
        "Before accepting instructions on a new matter, the firm conducts conflict checks against its existing client base and a check of the prospective client's identity and (for corporate clients) corporate ownership. The firm may decline to act, or withdraw from acting, if a conflict emerges or if the firm is unable to satisfy itself as to identity.",
      ],
    },
    {
      heading: "Confidentiality",
      paragraphs: [
        "The firm holds information communicated to it by clients in confidence and does not disclose it without the client's instruction except where required by law, by court order, or by the firm's professional conduct obligations under the Bangladesh Bar Council framework.",
      ],
    },
    {
      heading: "File handling and retention",
      paragraphs: [
        "Files are retained on closure of a matter for the period required by the firm's professional obligations and applicable limitation periods, typically seven years from the conclusion of the matter. After that period, files are securely destroyed unless the firm has been instructed to hold them for longer.",
        "Original documents provided by the client are returned on closure of the matter, on request.",
      ],
    },
    {
      heading: "Complaints",
      paragraphs: [
        "A client who is not satisfied with any aspect of the firm's service may raise the matter in writing with the principal of the firm at imran.gazi@gazilegal.com. The firm aims to respond to complaints within 14 days and to resolve them where possible at the level of the principal of the firm. The firm's regulatory framework under the Bangladesh Legal Practitioners and Bar Council Order 1972 provides for further recourse where matters cannot be resolved at firm level.",
      ],
    },
    {
      heading: "Limitation of liability",
      paragraphs: [
        "The firm's liability on any matter is limited to the lower of the fees paid on that matter and any amount specified in the engagement letter. The firm does not exclude or limit liability for fraud or for any liability that cannot be excluded under Bangladesh law.",
      ],
    },
    {
      heading: "Governing law",
      paragraphs: [
        "These terms and any engagement entered into on the basis of them are governed by the law of Bangladesh, and the courts of Bangladesh have exclusive jurisdiction over any dispute arising out of them.",
      ],
    },
  ],
} as const;
